// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrivnwcviszyrefhuste.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlyaXZud2N2aXN6eXJlZmh1c3RlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMjg3MjgsImV4cCI6MjA3MTYwNDcyOH0.TnI-4fOFJMQx2ou0iY5UUCA4TH7Rqf3XQTCZkXOdLYM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});